### ISSUE TITLE
swagger-ui.html not parsing when starting web application

### ISSUE THREAD

**Issue by Robert-Leggett** [springfox/springfox-demos#1]
Hi,

I am not able to get springfox-swagger-ui to work on a spring mvc restful api, the springfox-swagger2 is functional and producing json but when trying the start the web application it fails with a parsing error for swagger-ui.html.

I have created a thread on stackoverflow.

http://stackoverflow.com/questions/29897685/not-able-to-get-springfox-swagger-ui-working-with-spring-mvc

**Comment by adrianbk** [comment]
@Robert-Leggett here's an example using vanilla spring with XML configuration: https://github.com/springfox/springfox-demos/tree/master/spring-xml-swagger

And Vanilla spring with java config: https://github.com/springfox/springfox-demos/tree/master/spring-java-swagger

It looks like spring is trying to parse `swager-ui.html` as source of bean definitions - is there something in your app configuring spring to consider everything under `/META-INF/resources/` as a spring xml configuration?

**Comment by adrianbk** [comment]
I suspect your `contextConfigLocation `  value of `*` .

**Comment by Robert-Leggett** [comment]
@adrianbk thank you, you were right about the context config location, i have now corrected the code and fixed the issue I was having.

thanks
