### ISSUE TITLE
Misspelling in the description

### ISSUE THREAD

**Issue by kevlened** [springfox/springfox-demos#13]
`Springox demo applications` should be `Springfox demo applications`

**Comment by dilipkrish** [comment]
PR?

**Comment by kevlened** [comment]
Unfortunately, the description isn't part of the repo, so I can't provide a PR

<img width="342" alt="screen shot 2015-12-10 at 9 43 59 am" src="https://cloud.githubusercontent.com/assets/955312/11723289/9dd6fc68-9f22-11e5-9767-4b66fdff0331.png">

**Comment by dilipkrish** [comment]
Fixed thanks!
