### ISSUE TITLE
authorization - httpauth.  How to do it right?

### ISSUE THREAD

**Issue by ssrini** [springfox/springfox-demos#17]
This is snippet of my code from SwaggerConfiguration:

   	AuthorizationScope[] authScopes = new AuthorizationScope[1];
        authScopes[0] = new AuthorizationScopeBuilder()
                .scope("read")
                .description("Read Access")
                .build();

        SecurityReference securityReference = SecurityReference.builder()
                .reference("test")
                .scopes(authScopes)
                .build();

		ArrayList<SecurityReference> reference = new ArrayList(1);
        reference.add(securityReference);

        ArrayList<SecurityContext> securityContexts = new ArrayList(1);
        securityContexts.add(SecurityContext.builder().securityReferences(reference).build());

        ArrayList<SecurityScheme> auth = new ArrayList(1);
        auth.add(new BasicAuth("test"));

        return new Docket(DocumentationType.SWAGGER_2)
        	.securitySchemes(auth)
        	.securityContexts(securityContexts)
        	.select()
			.apis(RequestHandlerSelectors.withClassAnnotation(Api.class)) 
            .paths(regex("/API/v2/.*"))
            .build()
          	.pathMapping("/")
          	.protocols(protocols)
          	.apiInfo(metadata());
    }

When I use the generated json or directly access swagger-ui and try to hit the URL, the basic authentication used above does not seem to work.  Does not ask for credentials and also just keeps returning 0 although the URL is correct.

Any hints on where this is going wrong?

**Comment by dilipkrish** [comment]
Your doing everything correctly. Just to clarify, what you have done above is to _describe your security in a swagger dialect_. What you  also need to do is to ___implement the security___ using spring-security.

**Comment by ssrini** [comment]
Dilip

Something is not right.  

Here is the code snippet I used:

    	AuthorizationScope[] authScopes = new AuthorizationScope[1];
        authScopes[0] = new AuthorizationScopeBuilder()
                .scope("")
                .build();

        SecurityReference securityReference = SecurityReference.builder()
                .reference("basicAuth")
                .scopes(authScopes)
                .build();

		ArrayList<SecurityReference> reference = new ArrayList<SecurityReference>(1);
        reference.add(securityReference);


        ArrayList<SecurityContext> securityContexts = new ArrayList<SecurityContext>(1);
        securityContexts.add(SecurityContext.builder().securityReferences(reference).build());

        ArrayList<SecurityScheme> auth = new ArrayList<SecurityScheme>(1);
        auth.add(new BasicAuth("basicAuth"));
        
        Documentation Doc = new DocumentationBuilder().basePath("/UMP").build();

        return new Docket(DocumentationType.SWAGGER_2)
        	.pathProvider(new UMPPathProvider())
        	.securitySchemes(auth)
        	.securityContexts(securityContexts)
        	.select()
			.apis(RequestHandlerSelectors.withClassAnnotation(Api.class)) 
            .paths(regex("/API/v2/.*"))
            .build()
          	.pathMapping("/")
          	.host("demo.unvired.io")
          	.protocols(protocols)
          	.apiInfo(apiInfo());
    }

As you can notice, I had to add an empty scope else Springfox was failing with a null pointer exception.  Same problem if no scope was added (passed null).

The generated json is as follows:

    "securityDefinitions": {
        "basicAuth": {
            "type": "basic"
        }
    },
and in each API method the following snippet is included:
         "security": [
                    {
                        "basicAuth": [""]
                    }
                ],
If you open the HTTP Basic Auth example in the Swagger Editor website, the snippet is as follows:
"security": [
                    {
                        "basicAuth": []
                    }
                ],

When I used my generated JSON and pasted into the Swagger Editor, I see this error:
 Swagger Error Security scope definition could not be resolved.  The only way to resolve is to remove the empty quotes and have just the [].

Any ideas on how I can resolve this would be great.

Thanks

**Comment by ssrini** [comment]
Dilip,  for the record. I got over this issue by removing scope from the call ie.  Removed this line:

securityContexts(securityContexts)

Then I added the authorizations to the @Api annotation and the generated json is perfect.

**Comment by mehulparmar** [comment]
@ssrini This is exactly what I was looking for my project. Thanks!

**Comment by andrew-garland** [comment]
@ssrini BTW, you could have applied security across all endpoints in your docket if you made a small change above.

Instead of

```java
AuthorizationScope[] authScopes = new AuthorizationScope[1];
    authScopes[0] = new AuthorizationScopeBuilder()
            .scope("")
            .build();
```

you could have done:

`AuthorizationScope[] authScopes = new AuthorizationScope[0];`

Then your generated security would have had an empty list instead of a list that included `""`
