### ISSUE TITLE
@ApiImplicitParam not generating the correct type for integer

### ISSUE THREAD

**Issue by ssrini** [springfox/springfox-demos#18]
I have the following annotation:
@ApiImplicitParam(name = "limit", value = "Limit the number of users returned [1-N]", required = true, dataType = "integer", paramType = "query"),

The generated datatype (as seen in swagger-ui) is marked as undefined.  What is the correct type to use for integer?

**Comment by dilipkrish** [comment]
I think its `int`

**Comment by ssrini** [comment]
int worked .. don't know how I missed something so rudimentary.  Thanks

**Comment by Trii** [comment]
This got me today since I mistakenly though that it would be the swagger type for `integer` instead of the java primitive `int`. I was basing it off of code in https://github.com/springfox/springfox/issues/755
