### ISSUE TITLE
Documentation - basePath how to use?

### ISSUE THREAD

**Issue by ssrini** [springfox/springfox-demos#19]
Another beginner question .. searched but could not find any documents or examples.

By default the basePath in the swagger-ui is always shown as swagger-java since i am using that project.  How do i change that to the right basePath?

I can see that Documentation has a basePath setting.  But could not figure out how to link Documentation to Docket or other class?

Thanks in advance.

**Comment by dilipkrish** [comment]
You should be able to use the docket to provide a custom `PathProvider` and in that custom path provider use the `getApplicationBasePath()` to return the value that you need 
depending on how much customization you need to make you could use the `AbsrtractPathProvider` as a start. 

Looking to make this easier

**Comment by ssrini** [comment]
Thanks Dilip.  This worked great.
