### ISSUE TITLE
springfox-swagger-2.6.1 cannot find swagger-resources when run outside of spring boot 1.3

### ISSUE THREAD

**Issue by dansupriti** [springfox/springfox-demos#31]
Hi, 
I am using springfox-swagger2 -2.6.1 with springboot 1.3. Now when I run the application and try to see swagger dynamic documentation through web browser using http://localhost:8080/<context-path>/swagger-ui.html, I am not getting expected output, instead of that I am getting UI error -as mentioned below

 GET http://localhost:8080/webjars/springfox-swagger-ui/images/favicon-32x32.png 405 ()

GET http://localhost:8080/webjars/springfox-swagger-ui/springfox.js 405()

as suggested by other post I have added WebConfig as well

@Configuration
@EnableWebMvc
public class WebConfig extends WebMvcConfigurerAdapter {
	@Override
	public void addResourceHandlers(ResourceHandlerRegistry registry) {
		registry.addResourceHandler("swagger-ui.html").addResourceLocations("classpath:/META-INF/resources/");
		registry.addResourceHandler("**/webjars/**")
				.addResourceLocations("classpath:/META-INF/resources/webjars/");
	}
}

but still facing the same issue.

Any help is greatly appreciated

**Comment by dilipkrish** [comment]
Do you have spring security enabled perhaps? Definitely remove `@EnableWebMvc` if you're using spring boot

**Comment by dansupriti** [comment]
@dilipkrish .... Thanks for your reply..In my project we are not using Spring security. 
Let me tell you in detail ,say in my current application I have  4 Rest controller among those 4 one of the controller using Map to retrieve the value of path variable. Now if I commented out that particular Controller(using Map for path variable) than when I am running my application, I am able to create swagger dynamic documentation through web browser using http://localhost:8080//swagger-ui.html. But once I have commentated the said controller, swagger not able to generate the dynamic documentation.
Could please suggest something?
