### ISSUE TITLE
Swagger2 with Spring MVC

### ISSUE THREAD

**Issue by mihirlibran** [springfox/springfox-demos#32]
I have a Spring REST controller and I am trying to integrate Swagger2 into it. It is NOT a Spring Boot application. I am not trying to integrate swagger-ui as of now, but just trying to generate the JSON docs when I access http://localhost:8080/SwaggerTestProject/v2/api-docs I get a 404 error.

I have also looked at the Springfox demos and issue #14 , but to no avail.
Please find my Java files and my configuration files below.

jars under WEB-INF/lib
springfox-core-2.5.0
springfox-schema-2.5.0
springfox-spi-2.5.0
springfox-spring-web-2.5.0
springfox-swagger2-2.5.0
springfox-swagger-common-2.5.0

SwaggerConfig.java

```  
package com.swaggertest.config;
@Configuration
@EnableSwagger2
public class SwaggerConfig {

	@Bean
	public Docket api(){
		return new Docket(DocumentationType.SWAGGER_2)
				.select()
				.apis(RequestHandlerSelectors.any())
				.paths(PathSelectors.any())
				.build()
				.apiInfo(apiInfo());
	}
	
	private ApiInfo apiInfo(){
		return new ApiInfoBuilder()
				.title("TITLE")
				.description("DESCRIPTION")
				.version("VERSION")
				.license("LICENSE")
				.build();
	}	
}
```

TestController.java

```
package com.swaggertest.controller;
@Controller
@RequestMapping("/test")
public class TestController {

	@RequestMapping(value = "/testmethod", method = RequestMethod.GET , produces="application/json")
	public ResponseEntity<?> testMethod(){
		return new ResponseEntity<>("Hello world", HttpStatus.OK);
	}
}
```

My Spring configuration in /WEB-INF/spring-servlet.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:mvc="http://www.springframework.org/schema/mvc"
	xmlns:context="http://www.springframework.org/schema/context" xmlns:p="http://www.springframework.org/schema/p"
	xmlns:aop="http://www.springframework.org/schema/aop" xmlns:util="http://www.springframework.org/schema/util"
	xsi:schemaLocation="
        http://www.springframework.org/schema/mvc http://www.springframework.org/schema/mvc/spring-mvc-3.2.xsd
		http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context-3.2.xsd
        http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.2.xsd
        http://www.springframework.org/schema/aop http://www.springframework.org/schema/aop/spring-aop.xsd
        http://www.springframework.org/schema/util http://www.springframework.org/schema/util/spring-util-3.0.xsd">

	<context:component-scan base-package="com.swaggertest.controller" />
	<context:component-scan base-package="com.swaggertest.config" />

	<mvc:annotation-driven />

</beans>

```
I am not sure if I need a class which extends the WebMvcConfigurerAdapter.

I have configured my project as a Dynamic Web Project in Eclipse. I have configured Apache Tomcat 7.0.70 in Eclipse and I run my project by right-clicking on the project and selecting Run on Server.
Again I am not trying to set up Swagger UI but just want to generate the JSON docs of my APIs.

I believe I am missing something really simple. Any help will be appreciated. Thanks in advance!

**Comment by dilipkrish** [comment]
You need to `EnableWebMvc` via an annotation

**Comment by mihirlibran** [comment]
Thanks, that worked!

**Comment by niculistana** [comment]
@dilipkrish Why is `EnableWebMvc` annotation required here? Is it because there's something hardcoded in the springfox library? Currently facing the issue, but prefer to use `<mvc:annotation-driven` instead since I am working on a legacy project.

**Comment by dilipkrish** [comment]
@niculistana this is from 2016.
