### ISSUE TITLE
Question about springfox 2.0 and swagger ui?

### ISSUE THREAD

**Issue by glencurran** [springfox/springfox-demos#4]
So i changed over to springfox 2.0 and am trying to get the spring-boot demo working.

I have everything needed eg petstore etc. I put the contents of the dist folder from swagger ui in src/main/webapp/swagger folder and in the index.html I changed the line url = "http://petstore.swagger.io/v2/swagger.json"; to  url = "http://localhost:8080/api-docs"; so when I run it and go to http://localhost:8080/swagger/index.html shouldn't it display the api?

On another note in before when configuring swagger you could add ".includePatterns()" but I don't see this in the new version so how does it read in endpoints to include?

Hope this makes sense and if it doesn't I apologise, I've only been using swagger and related libraries for a week and a lot of what I have figured out has just been trial and error.

**Comment by dilipkrish** [comment]
Couple of things, we have support of using swagger ui natively you just need to pull in the [springfox-swagger-ui dependency](http://springfox.github.io/springfox/docs/snapshot/#getting-started).  

Also there is a [transition guide](http://springfox.github.io/springfox/docs/snapshot/#moving-from-swagger-springmvc) in the documentation

**Comment by glencurran** [comment]
Brilliant thanks for the quick response, I will go through these.
