### ISSUE TITLE
Property Key Value not working

### ISSUE THREAD

**Issue by n614cd** [springfox/springfox-demos#41]
Property values are not being substituted.
So I am attempting to debug. However, I cannot find the point in the swagger code where the substitution is occurring.  If you point me to this location, I can chase it further and see what the issue is.
Spring 4.2
XML Configuration
Gradle

(Specifically for ApiOperation.notes)

Thanks,

Tim

**Comment by dilipkrish** [comment]
What version of the library are you using? Most likely if you upgrade to 2.7.0 your problem will go away

**Comment by n614cd** [comment]
Version 2.7.0
Forgot to include in the description.

**Comment by n614cd** [comment]
Found issue. Legacy application based on old Spring XML config was not picking up the env resources correctly. For now, just hacked legacy structure to force properties to load.
