### ISSUE TITLE
Not able to see swagger-ui.html with SpringFox 3.0.0-SNAPSHOT library

### ISSUE THREAD

**Issue by prabhushrikant** [springfox/springfox-demos#70]
I am using springfox-integration-webmvc project and updated build.gradle to have springfox 3.0.0-SNAPSHOT dependencies

```
repositories {
  mavenCentral()
  maven { url 'http://oss.jfrog.org/artifactory/oss-snapshot-local/' }
  
}
```

Project now builds and endpoints are working well however the swagger page never shows up at http://localhost:8080/swagger-ui.html , I don't see any error logged as well when I hit swagger-ui.html.

I see following error.

![image](https://user-images.githubusercontent.com/6848200/86983793-aac08480-c141-11ea-9603-bb8a342860c7.png)

**Comment by dilipkrish** [comment]
https://github.com/springfox/springfox/issues/3362

**Comment by dilipkrish** [comment]
Also there is the [README](https://github.com/springfox/springfox-demos/blob/master/boot-webmvc/README.md) and the Have you read [the docs](http://springfox.github.io/springfox/docs/snapshot/) that explains this change

**Comment by prabhushrikant** [comment]
> [springfox/springfox#3362](https://github.com/springfox/springfox/issues/3362)

We are trying to get @Example & @ExampleProperty , is it supported by SpringFox 2.10.5 or do I have to wait for 3.0.0 to be released this week?

**Comment by prabhushrikant** [comment]
> Also there is the [README](https://github.com/springfox/springfox-demos/blob/master/boot-webmvc/README.md) and the Have you read [the docs](http://springfox.github.io/springfox/docs/snapshot/) that explains this change

which section of the document you are referring to exactly ?

**Comment by prabhushrikant** [comment]
I was able to get swagger up at location http://localhost:8080/swagger-ui/index.html on project springfox-integration-webmvc

**Comment by dilipkrish** [comment]
Thanks for reporting back! Please create an issue on the main project for the example problem
